services:
  pg:
    image: pgvector/pgvector:pg17
    container_name: nlw_agents_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agents
    ports:
      - 5432:5432
    volumes:
      - ./server/docker/setup_database.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nlw_agents_server
    image: nlw_agents_server:dev
    command: ["sh", "docker/start.sh"]
    # command: npm run dev
    stop_signal: SIGKILL # Use SIGKILL because the command is a sh script
    tty: true
    stdin_open: true
    ports:
      - 3333:3333 # For the server
      - 4983:4983 # For drizzle studio
    depends_on:
      - pg
    volumes:
      - ./server:/app

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: nlw_agents_web
    image: nlw_agents_web:dev
    command: ["sh", "docker/start.sh"]
    # command: npm run dev
    stop_signal: SIGKILL # Use SIGKILL because the command is a sh script
    tty: true
    stdin_open: true
    ports:
      - 5173:5173 # For the dev server
    depends_on:
      - server
    volumes:
      - ./web:/app

volumes:
  db_data:
