FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
# COPY package*.json ./
# RUN npm install

# Copy application source
# COPY . .

# Expose application port (change if needed)
EXPOSE 3333

# Start the application
# CMD ["node", "index.js"]
CMD ["npm", "run", "dev"]
